// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { Stimulus } from '../libs/stimulus'


import FilepondController from './filepond_controller'
Stimulus.register('filepond', FilepondController)

import FilterController from './filter_controller'
Stimulus.register('filter', FilterController)

import FlashController from './flash_controller'
Stimulus.register('flash', FlashController)

import HelloController from './hello_controller'
Stimulus.register('hello', HelloController)

import InventoryController from './inventory_controller'
Stimulus.register('inventory', InventoryController)

import ObliterateController from './obliterate_controller'
Stimulus.register('obliterate', ObliterateController)

import ReloadController from './reload_controller'
Stimulus.register('reload', ReloadController)